### ISSUE TITLE
[e-Internalisation] html roundtripping: wrong indices cause bad html

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#55] opened 2016-07-06 15:50 UTC
> when I run following curl, the returned HTML is all mangled up, it's like the spans are placed one letter too much to the right.
> 
> ```
> `curl 'http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all' -H 'Origin: http://localhost:63343' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-GB,en-US;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2782.1 Safari/537.36' -H 'Content-Type: text/html' -H 'Accept: text/n3' -H 'Referer: http://localhost:63343/CKEditor-Plugin/ckeditor/samples/freme.html?_ijt=1f2h7b8k9q28rg7m6ubdcq7hii' -H 'Connection: keep-alive' --data-binary '<p>Dissident Chinese artist Ai Weiwei has been refused a six-month visa by the British government amid claims he lied on his visa application form. Ai posted a letter on Instagram stating his entry to the UK had been restricted because he failed to declare his "criminal conviction". But Ai, though detained in China for 81 days in 2011, has never been charged or convicted of a crime in China. The artist was granted a 20-day visa to attend the opening of his London show.</p>' --compressed
> ```

**Comment by fsasaki** [comment] 2016-07-27 06:13
@ArneBinder and @katia-vistatec , is this is duplicate of https://github.com/freme-project/basic-services/issues/60 ?

**Comment by jnehring** [comment] 2016-07-27 07:22
Looks like a dublicate of #60. I tested it and I think the issue is resolved. @ArneBinder  can you please confirm and close the issue when it is fixed? This input

``` 
<p>Dissident Chinese artist Ai Weiwei has been refused a six-month
	visa by the British government amid claims he lied on his visa
	application form. Ai posted a letter on Instagram stating his entry to
	the UK had been restricted because he failed to declare his "criminal
	conviction". But Ai, though detained in China for 81 days in 2011, has
	never been charged or convicted of a crime in China. The artist was
	granted a 20-day visa to attend the opening of his London show.</p>
```	

produces this output

```
<p>
	Dissident <span
		data-its-ta-class-refs="http://dbpedia.org/ontology/Language http://www.w3.org/2002/07/owl#Thing"
		its-ta-class-ref="http://dbpedia.org/ontology/Language"
		its-ta-confidence="0.8768297988175746"
		its-ta-ident-ref="http://dbpedia.org/resource/Chinese_language">Chinese</span>
	artist <span
		data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Person http://dbpedia.org/ontology/Agent http://dbpedia.org/ontology/Person http://dbpedia.org/ontology/Artist"
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person"
		its-ta-confidence="0.9718246960349378"
		its-ta-ident-ref="http://dbpedia.org/resource/<span its-ta-class-ref="
		http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.576344061630415"
		its-ta-ident-ref="http://dbpedia.org/resource/Artificial_intelligence"><span
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location"
		its-ta-confidence="0.4120373593663368"
		its-ta-ident-ref="http://dbpedia.org/resource/Artificial_intelligence">Ai</span></span>_Weiwei">Ai
	Weiwei</span> has been refused a six-month visa by the <span
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization"
		its-ta-confidence="0.6656248757521315"
		its-ta-ident-ref="http://dbpedia.org/resource/Government_of_the_United_Kingdom">British
		government</span> amid claims he lied on his visa application form. Ai posted
	a letter on <span
		data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Organization http://dbpedia.org/ontology/Software http://dbpedia.org/ontology/Work"
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization"
		its-ta-confidence="0.41672582730870034"
		its-ta-ident-ref="http://dbpedia.org/resource/Instagram">Instagram</span>
	stating his entry to the <span
		data-its-ta-class-refs="http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Country http://nerd.eurecom.fr/ontology#Location"
		its-ta-class-ref="http://dbpedia.org/ontology/Location"
		its-ta-confidence="0.987058692626895"
		its-ta-ident-ref="http://dbpedia.org/resource/United_Kingdom">UK</span>
	had been restricted because he failed to declare his criminal
	conviction. But Ai, though detained in <span
		data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Country http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace"
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location"
		its-ta-confidence="0.997960791639201"
		its-ta-ident-ref="http://dbpedia.org/resource/<span data-its-ta-class-refs="
		http://dbpedia.org/ontology/Location
		http://nerd.eurecom.fr/ontology#Location
		http://dbpedia.org/ontology/Country
		http://dbpedia.org/ontology/PopulatedPlace
		http://dbpedia.org/ontology/Place" its-ta-class-ref="http://dbpedia.org/ontology/Location"
		its-ta-confidence="0.9966052698102266"
		its-ta-ident-ref="http://dbpedia.org/resource/China">China</span>">China</span>
	for 81 days in 2011, has never been charged or convicted of a crime in
	China. The artist was granted a 20-day visa to attend the opening of
	his <span
		data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Settlement http://dbpedia.org/ontology/PopulatedPlace"
		its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location"
		its-ta-confidence="0.9462773207624285"
		its-ta-ident-ref="http://dbpedia.org/resource/London">London</span>
	show.
</p> 
```

**Comment by katia-vistatec** [comment] 2016-07-27 08:09
Yes.

**Comment by ArneBinder** [comment] 2016-08-01 13:42
> Looks like a dublicate of #60. I tested it and I think the issue is resolved. @ArneBinder can you please confirm and close the issue when it is fixed? This input

@jnehring the output is still wrong for the input you mentioned above. Have a look at the first span that contains `Ai Weiwei`.

**Comment by jnehring** [comment] 2016-08-01 14:31
I just tried the service again. The output is

```
<p>Dissident 
    <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Person http://dbpedia.org/ontology/WrittenWork http://dbpedia.org/ontology/Work" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.5417612530509404" its-ta-ident-ref="http://de.dbpedia.org/resource/
        <span data-its-ta-class-refs="http://dbpedia.org/ontology/Work http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/WrittenWork" its-ta-class-ref="http://dbpedia.org/ontology/Work" its-ta-confidence="0.9971847120304276" its-ta-ident-ref="http://de.dbpedia.org/resource/
            <span data-its-ta-class-refs="http://dbpedia.org/ontology/Work http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/WrittenWork" its-ta-class-ref="http://dbpedia.org/ontology/Work" its-ta-confidence="0.9971287855430829" its-ta-ident-ref="http://de.dbpedia.org/resource/China">China</span>">China
        </span>">Chinese
    </span> artist
    <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Person http://dbpedia.org/ontology/Agent http://dbpedia.org/ontology/Person" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.6190995744207053" its-ta-ident-ref="http://de.dbpedia.org/resource/Ai_Weiwei">Ai Weiwei</span> has been refused a six-month visa by the British government amid claims he lied on his visa application form. Ai posted a letter on Instagram stating his
    <span its-ta-class-ref="http://www.w3.org/2002/07/owl#Thing" its-ta-confidence="0.6483413203494297">entry to the UK</span> had been restricted because he failed to declare his criminal conviction.
    <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.4450899019286688">But Ai</span>, though detained in China for 81 days in 2011, has never been charged or convicted of a crime in China. The artist was granted a 20-day visa to attend the opening of his
    <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/Place" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.8634146272389075" its-ta-ident-ref="http://de.dbpedia.org/resource/London">London</span> show.
</p>
```

Which looks good IMO.

**Comment by jnehring** [comment] 2016-08-01 15:30
It still does not work. @katia-vistatec can you please check whats wrong?

**Comment by katia-vistatec** [comment] 2016-08-02 08:07
Hi.
What's wrong in the output?

**Comment by jnehring** [comment] 2016-08-02 08:13
Line 3 starts with a span tag. Line 2 ends right in the middle of an attribute, neither the attribute nor the span tag of line 2 are properly closed. The same happens between line 3 and 4. Line 4 contains twice the word "china". Line 5 does not look ok with `</span>">Chinese`.

**Comment by katia-vistatec** [comment] 2016-08-02 08:41
[issue55.txt](https://github.com/freme-project/basic-services/files/396167/issue55.txt)

**Comment by katia-vistatec** [comment] 2016-08-02 08:46
Hi Jan. I have this output with my local version which is different from the one on the repository (with a completely different algorithm).  I am obtaining this output with e-terminology service. I have only the term attributes. Are you using the same service for testing? If my solution is correct I should solve only one last problem (for instance if I have city and Capital city as enriched text I should choose only the wider matching).

**Comment by katia-vistatec** [comment] 2016-08-02 08:46
[issue55-out.txt](https://github.com/freme-project/basic-services/files/396179/issue55-out.txt)

**Comment by jnehring** [comment] 2016-08-04 07:58
The output you posted (issue55-out.txt) looks fine, except that now e-Internationalization creates again the `<html>` tags that were not there before. I used /e-entity/freme-ner and still get odd output. This cURL

```
curl -X POST -H "Content-Type: text/html" -H "Accept: text/html" -H "Cache-Control: no-cache" -H "Postman-Token: 81caa736-f612-9537-560b-54416b27ca70" -d '<p>Dissident Chinese artist Ai Weiwei has been refused a six-month
    visa by the British government amid claims he lied on his visa
    application form. Ai posted a letter on Instagram stating his entry to
    the UK had been restricted because he failed to declare his "criminal
    conviction". But Ai, though detained in China for 81 days in 2011, has
    never been charged or convicted of a crime in China. The artist was
    granted a 20-day visa to attend the opening of his London show.</p>
' "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"
```

produces

```
<html>
    <head></head>
    <body>
        <p>Dissident 
            <span data-its-ta-class-refs="http://dbpedia.org/ontology/Language http://www.w3.org/2002/07/owl#Thing" its-ta-class-ref="http://dbpedia.org/ontology/Language" its-ta-confidence="0.8768297988175746" its-ta-ident-ref="http://dbpedia.org/resource/Chinese_language">Chinese</span> artist
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Person http://dbpedia.org/ontology/Agent http://dbpedia.org/ontology/Person http://dbpedia.org/ontology/Artist" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.576344061630415" its-ta-ident-ref="http://dbpedia.org/resource/Artificial_intelligence" http: nerd.eurecom.fr ntology#person">Ai</span>_Weiwei">Ai Weiwei has been refused a six-month visa by the
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization" its-ta-confidence="0.6656248757521315" its-ta-ident-ref="http://dbpedia.org/resource/Government_of_the_United_Kingdom">British government</span> amid claims he lied on his visa application form. Ai posted a letter on
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Organization http://dbpedia.org/ontology/Software http://dbpedia.org/ontology/Work" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization" its-ta-confidence="0.41672582730870034" its-ta-ident-ref="http://dbpedia.org/resource/Instagram">Instagram</span> stating his entry to the
            <span data-its-ta-class-refs="http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Country http://nerd.eurecom.fr/ontology#Location" its-ta-class-ref="http://dbpedia.org/ontology/Location" its-ta-confidence="0.987058692626895" its-ta-ident-ref="http://dbpedia.org/resource/United_Kingdom">UK</span> had been restricted because he failed to declare his criminal conviction. But Ai, though detained in
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Country http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.997960791639201" its-ta-ident-ref="http://dbpedia.org/resource/China">China</span> for 81 days in 2011, has never been charged or convicted of a crime in
            <span data-its-ta-class-refs="http://dbpedia.org/ontology/Location http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Country http://dbpedia.org/ontology/PopulatedPlace http://dbpedia.org/ontology/Place" its-ta-class-ref="http://dbpedia.org/ontology/Location" its-ta-confidence="0.9966052698102266" its-ta-ident-ref="http://dbpedia.org/resource/China">China</span>. The artist was granted a 20-day visa to attend the opening of his
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Settlement http://dbpedia.org/ontology/PopulatedPlace" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.9462773207624285" its-ta-ident-ref="http://dbpedia.org/resource/London">London</span> show.
        </p>
    </body>
</html>
```

This bit looks odd in line 6 : `Ai</span>_Weiwei"&gt;Ai Weiwei has been refused a six-month`.

And another thing that is odd: When I change the output to turtle then I get an annotation for char=26,35 to link `http://dbpedia.org/resource/Ai_Weiwei` and another one from char=146-148 to `http://dbpedia.org/resource/Artificial_intelligence`. But the annotation `its-ta-ident-ref="http://dbpedia.org/resource/Artificial_intelligence"` seems to point to the string `Ai` in line 6 which is character 26-35. So it seems that the annotation is not in the right place.

**Comment by katia-vistatec** [comment] 2016-08-12 13:39
@jnehring can you check if the output is correct now?

**Comment by fsasaki** [comment] 2016-08-13 07:24
Isn't it the underlying validator.nu library that add  the html tag etc.? See

https://github.com/freme-project/e-Internationalization/issues/31#issuecomment-169982438

**Comment by jnehring** [comment] 2016-08-15 07:54
> can you check if the output is correct now?

The output is now:

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-entity/freme-ner/documents",
  "message": "Error parsing NIF input",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1471247606038
}
```

**Comment by katia-vistatec** [comment] 2016-08-15 08:31
On Friday I hadn't this response.

**Comment by jnehring** [comment] 2016-08-15 12:36
The error parsing NIF happen due to another bug which I just solved. Now the output looks like this:

```
<html>
    <head></head>
    <body>
        <p>Dissident 
            <span its-ta-class-ref="http://www.w3.org/2002/07/owl#Thing" its-ta-confidence="0.8768297988175746" its-ta-ident-ref="http://dbpedia.org/resource/Chinese">Chinese</span> artist
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Person http://dbpedia.org/ontology/Agent http://dbpedia.org/ontology/Person http://dbpedia.org/ontology/Artist" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.9718246960349378" its-ta-ident-ref="http://dbpedia.org/resource/Ai_Weiwei">Ai Weiwei</span> has been refused a six-month visa by the
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization" its-ta-confidence="0.6656248757521315" its-ta-ident-ref="http://dbpedia.org/resource/British_Government">British government</span> amid claims he lied on his visa application form.
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person" its-ta-confidence="0.576344061630415" its-ta-ident-ref="http://dbpedia.org/resource/AI">Ai</span> posted a letter on
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Organization" its-ta-confidence="0.41672582730870034" its-ta-ident-ref="http://dbpedia.org/resource/INSTAGRAM">Instagram</span> stating his entry to the
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.987058692626895" its-ta-ident-ref="http://dbpedia.org/resource/.uk">UK</span> had been restricted because he failed to declare his criminal conviction. But
            <span its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.4120373593663368" its-ta-ident-ref="http://dbpedia.org/resource/AI">Ai</span>, though detained in
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Country http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.997960791639201" its-ta-ident-ref="http://dbpedia.org/resource/China">China</span> for 81 days in 2011, has never been charged or convicted of a crime in
            <span data-its-ta-class-refs="http://dbpedia.org/ontology/Location http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Country http://dbpedia.org/ontology/PopulatedPlace http://dbpedia.org/ontology/Place" its-ta-class-ref="http://dbpedia.org/ontology/Location" its-ta-confidence="0.9966052698102266" its-ta-ident-ref="http://dbpedia.org/resource/China">China</span>. The artist was granted a 20-day visa to attend the opening of his
            <span data-its-ta-class-refs="http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Settlement http://dbpedia.org/ontology/PopulatedPlace" its-ta-class-ref="http://nerd.eurecom.fr/ontology#Location" its-ta-confidence="0.9462773207624285" its-ta-ident-ref="http://dbpedia.org/resource/London">London</span> show.
        </p>
    </body>
</html>
```

All problems mentioned above are solved. But for some reason the system adds a `body` and `html`tag. It did not do this 14 fays ago.

**Comment by fsasaki** [comment] 2016-08-15 14:27
Isn't the reason the underlying validator.nu library? See
https://github.com/freme-project/e-Internationalization/issues/31#issuecomment-169986530

**Comment by jnehring** [comment] 2016-12-05 14:47
I tested it and this issue is fixed now.

**Closed by jnehring** 2016-12-05 14:47 UTC
Labels: bug
