### ISSUE TITLE
[Pipelines] error produced by individual pipeline steps are not part of the output 

### ISSUE THREAD

**Issue by fsasaki** [freme-project/basic-services#81] opened 2016-08-16 19:54 UTC
See an example at https://github.com/freme-project/basic-services/issues/77#issuecomment-240204372

**Comment by ArneBinder** [comment] 2016-08-16 22:26
This was caused by #82, not by the pipeline service. Can we close this?

**Comment by jnehring** [comment] 2016-08-17 07:14
I also think that sometimes the pipeline does not report errors back to the user. When I find an example then I will open a new issue for it.

**Closed by jnehring** 2016-08-17 07:14 UTC
Labels: bug
